### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by mokurin000** [MATRIX-feather/osu#2]
**游戏版本**
2020.130.1
**出现位置**
开始动画
**建议**
把”欢迎来到osu!“改回welcome to osu!

**Comment by MATRIX-feather** [comment]
建议已采纳, 目前的解决方案为在选择开始动画处新建两个选项, 用于选择原版的开始动画, 可能仍需要一些完善

**Comment by mokurin000** [comment]
感谢采纳
