### ISSUE TITLE
osu.Game.proj不能正确加载（编译时）

### ISSUE THREAD

**Issue by RocketMaDev** [MATRIX-feather/osu#34]
**Describe the bug:**   
在clone完以后进行dotnet restore的时候提示`跳过项目“D:\CPPProject\mfosu\osu.Game\osu.Game.csproj”，因为未找到该项目。`**（此处由于网速原因，我把你的仓库fork到了gitee，这里有不同之处，但出现的问题是相同的）**，我clone的路径是`\CPPProject\`，但它又加了一个`mfosu\`，导致在编译时找不到包了，这里是不是多加了一个`mfosu\`?

**Screenshots or videos showing encountered issue:**  
![Snipaste_2021-07-04_14-55-47](https://user-images.githubusercontent.com/48864431/124376114-f3206d00-dcd7-11eb-80a4-815b8710547a.png)   
![Snipaste_2021-07-04_14-52-21](https://user-images.githubusercontent.com/48864431/124376066-b785a300-dcd7-11eb-86e5-33d941dbd1fa.png)

**osu!lazer version:**   
Commit 4669bb3

**Logs:**

**Comment by RocketMaDev** [comment]
分支stable

**Comment by RocketMaDev** [comment]
是不是在`Mvis.Plugin.CloudMusicSupport.csproj`,`Mvis.Plugin.Yasp.csproj`中多加了`..\mfosu\`?  
![Snipaste_2021-07-04_15-12-57](https://user-images.githubusercontent.com/48864431/124376604-66c37980-dcda-11eb-86b4-51e6ca14e9ec.png)

**Comment by MATRIX-feather** [comment]
看了一下，确实多加了一个mfosu，已经在 https://github.com/MATRIX-feather/osu/commit/8753d821ea298f7429b2a1211cdc40b2d5af6a9f 修了，感谢指出！

**Comment by RocketMaDev** [comment]
在stable里contribute一下吧，以免后面的人编译失败
