### ISSUE TITLE
osu-framework需要同步!

### ISSUE THREAD

**Issue by RocketMaDev** [MATRIX-feather/osu#36]
**Describe the bug:**   
*stable分支*  
 WikiMarkdownImageBlock.cs中的CreateImageSprite()没有合适的方法重写  
`D:\CPPProject\mfosu\osu\osu.Game\Overlays\Wiki\Markdown\WikiMarkdownImageBlock.cs(66,43): error CS0115: “WikiMarkdownImageBlock.BlockMarkdownImage.BlockImageContainer.CreateImageSprite()”: 没有找到适合的方法来重写 [D:\CPPProject\mfosu\osu\osu.Game\osu.Game.csproj]`  
在`ppy/osu-framework`上存在`protected virtual Sprite CreateImageSprite();`而在你的`osu-framework`中缺失了，导致stable分支代码无法编译成功。  
**请更新一下osu-framework的custom分支！**

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:**   
ad225dd

**Logs:**

**Comment by MATRIX-feather** [comment]
重新推了一下代码，再构建一次试试？

**Comment by RocketMaDev** [comment]
行了！
