### ISSUE TITLE
Android版本文件导入路径似乎错误

### ISSUE THREAD

**Issue by RocketMaDev** [MATRIX-feather/osu#37]
当我升级到`709laser`（跳了2个发布版本）后，文件导入中的路径从`/emulated/0/...`变成了`/data/user/...`这样如果不root，是不能访问这个路径的，是不是改错了什么？求更新，这个功能在手机上对导入.osk,.osr很有用啊

**Comment by MATRIX-feather** [comment]
这应该是上游某次更改导致的问题，已在daily( https://github.com/MATRIX-feather/osu/commit/86804692c8f976c0b11ddf883d1ab8ebceefd4a4 )上修复

**Comment by RocketMaDev** [comment]
等着下一次的release
