### ISSUE TITLE
重写Sayobot加速

### ISSUE THREAD

**Issue by PercyDan54** [MATRIX-feather/osu#38]
目前通过传参数的方法太容易引起合并冲突

**Comment by PercyDan54** [comment]
更简单粗暴的解法：https://github.com/PercyDan54/osu/commit/b7102775239b7db649250db776ab13ecd54fe65b
（

**Comment by MATRIX-feather** [comment]
> 更简单粗暴的解法：[PercyDan54@b710277](https://github.com/PercyDan54/osu/commit/b7102775239b7db649250db776ab13ecd54fe65b) （

确实很粗暴（

https://github.com/MATRIX-feather/osu/commit/a50ccd1b67e03917b284e73205eb70c1480ec561
在171d7f4的基础上改了改，这次我打算把`UseSayobot`选项移除，让用户能自己选加速地址
